TEMPLATE = app
QT += network
unix:TARGET = ./../bin/skybotclient
win32:TARGET = ./../../bin/skybotclient
CONFIG   += console warn_off release
CONFIG   -= app_bundle
SOURCES += main.cpp
SOURCES += skybotclient.cpp
HEADERS += skybotclient.h
